server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Redirect all Angular routes to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static files
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2|ttf)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}
