// <auto-generated />
using System;
using CS2Ranking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CS2Ranking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202195036_CreateMatch")]
    partial class CreateMatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CS2Ranking.Domain.Entities.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PicturePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("picture_path");

                    b.HasKey("Id")
                        .HasName("pk_map");

                    b.ToTable("map", (string)null);
                });

            modelBuilder.Entity("CS2Ranking.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<string>("Gamemode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gamemode");

                    b.Property<int>("MapId")
                        .HasColumnType("integer")
                        .HasColumnName("map_id");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("score");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.HasKey("Id")
                        .HasName("pk_match");

                    b.ToTable("match", (string)null);
                });

            modelBuilder.Entity("CS2Ranking.Domain.Entities.MatchRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("RankId")
                        .HasColumnType("integer")
                        .HasColumnName("rank_id");

                    b.Property<int?>("RankScore")
                        .HasColumnType("integer")
                        .HasColumnName("rank_score");

                    b.HasKey("Id")
                        .HasName("pk_match_rank");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_rank_match_id");

                    b.ToTable("match_rank", (string)null);
                });

            modelBuilder.Entity("CS2Ranking.Domain.Entities.MatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adr")
                        .HasColumnType("integer")
                        .HasColumnName("adr");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer")
                        .HasColumnName("deaths");

                    b.Property<double>("Hltv")
                        .HasColumnType("double precision")
                        .HasColumnName("hltv");

                    b.Property<int>("Kills")
                        .HasColumnType("integer")
                        .HasColumnName("kills");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.HasKey("Id")
                        .HasName("pk_match_result");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_result_match_id");

                    b.ToTable("match_result", (string)null);
                });

            modelBuilder.Entity("CS2Ranking.Domain.Entities.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PicturePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("picture_path");

                    b.Property<int>("RatingMax")
                        .HasColumnType("integer")
                        .HasColumnName("rating_max");

                    b.Property<int>("RatingMin")
                        .HasColumnType("integer")
                        .HasColumnName("rating_min");

                    b.HasKey("Id")
                        .HasName("pk_rank");

                    b.ToTable("rank", (string)null);
                });

            modelBuilder.Entity("CS2Ranking.Domain.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_season");

                    b.ToTable("season", (string)null);
                });

            modelBuilder.Entity("CS2Ranking.Domain.Entities.MatchRank", b =>
                {
                    b.HasOne("CS2Ranking.Domain.Entities.Match", null)
                        .WithOne("MatchRank")
                        .HasForeignKey("CS2Ranking.Domain.Entities.MatchRank", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_rank_match_match_id");
                });

            modelBuilder.Entity("CS2Ranking.Domain.Entities.MatchResult", b =>
                {
                    b.HasOne("CS2Ranking.Domain.Entities.Match", null)
                        .WithOne("MatchResult")
                        .HasForeignKey("CS2Ranking.Domain.Entities.MatchResult", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_result_match_match_id");
                });

            modelBuilder.Entity("CS2Ranking.Domain.Entities.Match", b =>
                {
                    b.Navigation("MatchRank");

                    b.Navigation("MatchResult")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
