<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CS2Ranking.Application\CS2Ranking.Application.csproj" />
		<ProjectReference Include="..\CS2Ranking.Domain\CS2Ranking.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EFCore.NamingConventions" Version="8.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.8" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.10" />
	</ItemGroup>

</Project>
