version: '3.9'

services:
  main-api:
    build:
      context: ../Main
      dockerfile: Dockerfile.dev  
    container_name: cs2ranking-main-dev
    volumes:
      - ../Main:/src             
      - /src/bin
      - /src/obj
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"  
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "server=${DB_SERVER};port=${DB_PORT};database=${DB_NAME};user=${DB_USER};charset=utf8mb4"
      GoogleSheets__ApiKey: ${GOOGLESHEETS_APIKEY}
      ScopeGG__ScopeSessionId: ${SCOPE_SESSION_ID}
    ports:
      - "${MAIN_API_PORT}:8080"

  auth-service:
    build:
      context: ../Microservices/CS2Ranking.Authentication
      dockerfile: Dockerfile.dev
    container_name: cs2ranking-auth-dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "server=${DB_SERVER};port=${DB_PORT};database=${DB_NAME};user=${DB_USER};charset=utf8mb4"
      DOTNET_USE_POLLING_FILE_WATCHER: "true" 
    volumes:
      - ../Microservices/CS2Ranking.Authentication:/src
      - /root/.nuget/packages 
    ports:
      - "${AUTH_SERVICE_PORT}:8080"

  client:
    build:
      context: ../client
      dockerfile: Dockerfile.dev
    container_name: cs2ranking-client-dev
    volumes:
      - ../client:/app
      - /app/node_modules
    ports:
      - "${CLIENT_PORT}:4200"
    environment:
      CHOKIDAR_USEPOLLING: "true"
